--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

-- Started on 2025-06-20 09:51:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3325 (class 1262 OID 16398)
-- Name: proyecto_master; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE proyecto_master WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Colombia.1252';


ALTER DATABASE proyecto_master OWNER TO postgres;

\connect proyecto_master

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16407)
-- Name: _maestros_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public._maestros_ (
    idx integer NOT NULL,
    nombre character varying(100),
    apellidos character varying(100),
    email character varying(200),
    fecha_nacimiento bigint,
    estado smallint DEFAULT 0,
    descripcion character varying(300),
    telefono bigint,
    contrasenia character varying(300)
);


ALTER TABLE public._maestros_ OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16441)
-- Name: _maestros__idx_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public._maestros_ ALTER COLUMN idx ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public._maestros__idx_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3175 (class 2606 OID 16433)
-- Name: _maestros_ _maestros__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public._maestros_
    ADD CONSTRAINT _maestros__pkey PRIMARY KEY (idx);


--
-- TOC entry 3177 (class 2606 OID 16417)
-- Name: _maestros_ email_unico; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public._maestros_
    ADD CONSTRAINT email_unico UNIQUE (email);


--
-- TOC entry 3326 (class 0 OID 0)
-- Dependencies: 3325
-- Name: DATABASE proyecto_master; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE proyecto_master TO proyecto_master;


-- Completed on 2025-06-20 09:51:39

--
-- PostgreSQL database dump complete
--

